/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-05-21 16:45:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

response.setHeader("Cache-Control","no-cache"); //Forces caches to obtain a new copy of the page from the origin server
response.setHeader("Cache-Control","no-store"); //Directs caches not to store the page under any circumstance
response.setDateHeader("Expires", 0); //Causes the proxy cache to see the page as "stale"
response.setHeader("Pragma","no-cache"); //HTTP 1.0 backward compatibility


if(session.getAttribute("uid")==null || session.getAttribute("ps")==null)
	{
	
		response.sendRedirect("ErrorPage.jsp");
	
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"stmenu.js\"></script></head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("stm_bm([\"menu0f4d\",980,\"\",\"blank.gif\",4,\"\",\"\",0,0,250,0,1000,1,0,0,\"\",\"540\",67109119,0,1,2,\"default\",\"hand\",\"\",1,25],this);\r\n");
      out.write("stm_bp(\"p0\",[0,4,0,0,0,0,0,0,100,\"\",-2,\"\",-2,50,0,0,\"#799BD8\",\"transparent\",\"060417line.gif\",3,0,0,\"#000000\"]);\r\n");
      out.write("stm_ai(\"p0i0\",[0,\"HOME\",\"\",\"\",-1,-1,0,\"index.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"\",\"bg2.gif\",2,3,0,0,\"#FFFFF7\",\"#000000\",\"#66FFFF\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"\",\"bg1.gif\",\"\",\"bg3.gif\",6,6,26],90,26);\r\n");
      out.write("\r\n");
      out.write("stm_aix(\"p0i1\",\"p0i0\",[0,\"COMPLAINT CATEGORY\",\"\",\"\",-1,-1,0,\"\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"\",\"bg2.gif\",3],90,26);\r\n");
      out.write("stm_bpx(\"p1\",\"p0\",[0,4,0,0,0,0,0,0,100,\"\",-2,\"\",-2,78,0,0,\"#799BD8\",\"#EEEEEE\",\"060417line1.gif\"]);\r\n");
      out.write("stm_aix(\"p1i0\",\"p0i0\",[0,\"WOMEN/CHILD RELATED CRIME\",\"\",\"\",-1,-1,0,\"women.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],70,26);\r\n");
      out.write("stm_aix(\"p1i1\",\"p1i0\",[0,\"REPORT A CYBER CRIME\",\"\",\"\",-1,-1,0,\"cyber.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],70,26);\r\n");
      out.write("stm_aix(\"p1i2\",\"p1i1\",[0,\"FINANCIAL FRAUD\",\"\",\"\",-1,-1,0,\"financial.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],70,26);\r\n");
      out.write("stm_aix(\"p1i3\",\"p1i1\",[0,\"REPORT A RAPIST CRIME\",\"\",\"\",-1,-1,0,\"rape.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],70,26);\r\n");
      out.write("stm_aix(\"p1i4\",\"p1i1\",[0,\"REPORT A MURDERER CRIME\",\"\",\"\",-1,-1,0,\"murder.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],70,26);\r\n");
      out.write("stm_ep();\r\n");
      out.write("stm_aix(\"p0i2\",\"p0i1\",[0,\"CRIME STATISTICS\",\"\",\"\",-1,-1,0,\"static.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],90,26);\r\n");
      out.write("stm_aix(\"p0i3\",\"p0i2\",[0,\"FILE YOUR COMPLAINT\",\"\",\"\",-1,-1,0,\"file_track.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],90,26);\r\n");
      out.write("stm_aix(\"p0i4\",\"p0i2\",[0,\"TRACK YOUR COMPLAINT\",\"\",\"\",-1,-1,0,\"Track.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"060417line1.gif\",\"060417line1.gif\",3,3,0,0,\"#FFFFF7\",\"#000000\",\"#333399\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",\"060417line1.gif\",10,10],90,26);\r\n");
      out.write("stm_aix(\"p0i5\",\"p0i2\",[0,\"CONTACT US\",\"\",\"\",-1,-1,0,\"Contactus.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"\",\".gif\",2,3,0,0,\"#FFFFF7\",\"#000000\",\"#66FFFF\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"\",\"bg1.gif\",\"\",\"bg3.gif\",6,6,26],90,26);\r\n");
      out.write("stm_aix(\"p0i5\",\"p0i2\",[0,\"ABOUT US\",\"\",\"\",-1,-1,0,\"About.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"\",\".gif\",2,3,0,0,\"#FFFFF7\",\"#000000\",\"#66FFFF\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"\",\"bg1.gif\",\"\",\"bg3.gif\",6,6,26],90,26);\r\n");
      out.write("\r\n");
 if(session.getAttribute("uid")!=null && session.getAttribute("ps")!=null)
	
{

      out.write("\r\n");
      out.write("\r\n");
      out.write("stm_aix(\"p0i5\",\"p0i2\",[0,\"LOGOUT\",\"\",\"\",-1,-1,0,\"Logout.jsp\",\"_self\",\"\",\"\",\"\",\"\",0,0,0,\"\",\"\",0,0,0,1,1,\"#FFFFF7\",1,\"#B5BED6\",1,\"\",\".gif\",2,3,0,0,\"#FFFFF7\",\"#000000\",\"#66FFFF\",\"#FF0000\",\"bold 7pt Verdana\",\"bold 7pt Verdana\",0,0,\"\",\"bg1.gif\",\"\",\"bg3.gif\",6,6,26],90,26);\r\n");
      out.write("\r\n");

}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("stm_ep();\r\n");
      out.write("stm_em();\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
