/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-05-05 10:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SlidingImages_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>Jquery slider</title>\r\n");
      out.write("	<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("	<meta name=\"description\" content=\"Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Jquery slider\" />\r\n");
      out.write("	\r\n");
      out.write("	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"engine1/style.css\" />\r\n");
      out.write("	<script type=\"text/javascript\" src=\"engine1/jquery.js\"></script>\r\n");
      out.write("	<!-- End WOWSlider.com HEAD section -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#d7d7d7;margin:auto\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->\r\n");
      out.write("	<div id=\"wowslider-container1\">\r\n");
      out.write("	<div class=\"ws_images\"><ul>\n");
      out.write("		<li><img src=\"data1/images/112h.jpg\" alt=\"112h\" title=\"112h\" id=\"wows1_0\"/></li>\n");
      out.write("		<li><img src=\"data1/images/back.jpg\" alt=\"back\" title=\"back\" id=\"wows1_1\"/></li>\n");
      out.write("		<li><img src=\"data1/images/backg.jpg\" alt=\"backg\" title=\"backg\" id=\"wows1_2\"/></li>\n");
      out.write("		<li><img src=\"data1/images/cbi.png\" alt=\"cbi\" title=\"cbi\" id=\"wows1_3\"/></li>\n");
      out.write("		<li><img src=\"data1/images/cm_help.jpg\" alt=\"cm_help\" title=\"cm_help\" id=\"wows1_4\"/></li>\n");
      out.write("		<li><img src=\"data1/images/com.jpg\" alt=\"com\" title=\"com\" id=\"wows1_5\"/></li>\n");
      out.write("		<li><img src=\"data1/images/cool.png\" alt=\"cool\" title=\"cool\" id=\"wows1_6\"/></li>\n");
      out.write("		<li><img src=\"data1/images/cr.png\" alt=\"cr\" title=\"cr\" id=\"wows1_7\"/></li>\n");
      out.write("		<li><img src=\"data1/images/em.jpg\" alt=\"Em\" title=\"Em\" id=\"wows1_8\"/></li>\n");
      out.write("		<li><img src=\"data1/images/for.png\" alt=\"for\" title=\"for\" id=\"wows1_9\"/></li>\n");
      out.write("		<li><img src=\"data1/images/ggg.jpg\" alt=\"ggg\" title=\"ggg\" id=\"wows1_10\"/></li>\n");
      out.write("		<li><img src=\"data1/images/head.png\" alt=\"head\" title=\"head\" id=\"wows1_11\"/></li>\n");
      out.write("		<li><img src=\"data1/images/hh.jpg\" alt=\"hh\" title=\"hh\" id=\"wows1_12\"/></li>\n");
      out.write("		<li><img src=\"data1/images/in.png\" alt=\"in\" title=\"in\" id=\"wows1_13\"/></li>\n");
      out.write("		<li><img src=\"data1/images/logo.png\" alt=\"logo\" title=\"logo\" id=\"wows1_14\"/></li>\n");
      out.write("		<li><img src=\"data1/images/logo2.png\" alt=\"logo2\" title=\"logo2\" id=\"wows1_15\"/></li>\n");
      out.write("		<li><img src=\"data1/images/logo22.png\" alt=\"logo22\" title=\"logo22\" id=\"wows1_16\"/></li>\n");
      out.write("		<li><img src=\"data1/images/logo3.png\" alt=\"logo3\" title=\"logo3\" id=\"wows1_17\"/></li>\n");
      out.write("		<li><img src=\"data1/images/lp.jpg\" alt=\"lp\" title=\"lp\" id=\"wows1_18\"/></li>\n");
      out.write("		<li><img src=\"data1/images/star.jpg\" alt=\"star\" title=\"star\" id=\"wows1_19\"/></li>\n");
      out.write("		<li><a href=\"http://wowslider.net\"><img src=\"data1/images/temp.jpg\" alt=\"javascript photo gallery\" title=\"temp\" id=\"wows1_20\"/></a></li>\n");
      out.write("		<li><img src=\"data1/images/w.jpg\" alt=\"w\" title=\"w\" id=\"wows1_21\"/></li>\n");
      out.write("	</ul></div>\n");
      out.write("	<div class=\"ws_bullets\"><div>\n");
      out.write("		<a href=\"#\" title=\"112h\"><span><img src=\"data1/tooltips/112h.jpg\" alt=\"112h\"/>1</span></a>\n");
      out.write("		<a href=\"#\" title=\"back\"><span><img src=\"data1/tooltips/back.jpg\" alt=\"back\"/>2</span></a>\n");
      out.write("		<a href=\"#\" title=\"backg\"><span><img src=\"data1/tooltips/backg.jpg\" alt=\"backg\"/>3</span></a>\n");
      out.write("		<a href=\"#\" title=\"cbi\"><span><img src=\"data1/tooltips/cbi.png\" alt=\"cbi\"/>4</span></a>\n");
      out.write("		<a href=\"#\" title=\"cm_help\"><span><img src=\"data1/tooltips/cm_help.jpg\" alt=\"cm_help\"/>5</span></a>\n");
      out.write("		<a href=\"#\" title=\"com\"><span><img src=\"data1/tooltips/com.jpg\" alt=\"com\"/>6</span></a>\n");
      out.write("		<a href=\"#\" title=\"cool\"><span><img src=\"data1/tooltips/cool.png\" alt=\"cool\"/>7</span></a>\n");
      out.write("		<a href=\"#\" title=\"cr\"><span><img src=\"data1/tooltips/cr.png\" alt=\"cr\"/>8</span></a>\n");
      out.write("		<a href=\"#\" title=\"Em\"><span><img src=\"data1/tooltips/em.jpg\" alt=\"Em\"/>9</span></a>\n");
      out.write("		<a href=\"#\" title=\"for\"><span><img src=\"data1/tooltips/for.png\" alt=\"for\"/>10</span></a>\n");
      out.write("		<a href=\"#\" title=\"ggg\"><span><img src=\"data1/tooltips/ggg.jpg\" alt=\"ggg\"/>11</span></a>\n");
      out.write("		<a href=\"#\" title=\"head\"><span><img src=\"data1/tooltips/head.png\" alt=\"head\"/>12</span></a>\n");
      out.write("		<a href=\"#\" title=\"hh\"><span><img src=\"data1/tooltips/hh.jpg\" alt=\"hh\"/>13</span></a>\n");
      out.write("		<a href=\"#\" title=\"in\"><span><img src=\"data1/tooltips/in.png\" alt=\"in\"/>14</span></a>\n");
      out.write("		<a href=\"#\" title=\"logo\"><span><img src=\"data1/tooltips/logo.png\" alt=\"logo\"/>15</span></a>\n");
      out.write("		<a href=\"#\" title=\"logo2\"><span><img src=\"data1/tooltips/logo2.png\" alt=\"logo2\"/>16</span></a>\n");
      out.write("		<a href=\"#\" title=\"logo22\"><span><img src=\"data1/tooltips/logo22.png\" alt=\"logo22\"/>17</span></a>\n");
      out.write("		<a href=\"#\" title=\"logo3\"><span><img src=\"data1/tooltips/logo3.png\" alt=\"logo3\"/>18</span></a>\n");
      out.write("		<a href=\"#\" title=\"lp\"><span><img src=\"data1/tooltips/lp.jpg\" alt=\"lp\"/>19</span></a>\n");
      out.write("		<a href=\"#\" title=\"star\"><span><img src=\"data1/tooltips/star.jpg\" alt=\"star\"/>20</span></a>\n");
      out.write("		<a href=\"#\" title=\"temp\"><span><img src=\"data1/tooltips/temp.jpg\" alt=\"temp\"/>21</span></a>\n");
      out.write("		<a href=\"#\" title=\"w\"><span><img src=\"data1/tooltips/w.jpg\" alt=\"w\"/>22</span></a>\n");
      out.write("	</div></div><div class=\"ws_script\" style=\"position:absolute;left:-99%\"><a href=\"http://wowslider.net\">jquery slider</a> by WOWSlider.com v9.0</div>\r\n");
      out.write("	<div class=\"ws_shadow\"></div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	<script type=\"text/javascript\" src=\"engine1/wowslider.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"engine1/script.js\"></script>\r\n");
      out.write("	<!-- End WOWSlider.com BODY section -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
